package(default_visibility = ["//visibility:public"])

filegroup(
    name = "map_sunnyvale_big_loop",
    testonly = True,
    srcs = glob([
        "sunnyvale_big_loop/**",
    ]),
)

filegroup(
    name = "map_sunnyvale_loop",
    testonly = True,
    srcs = glob([
        "sunnyvale_loop/**",
    ]),
)


filegroup(
    name = "highway",
    srcs = glob([
        "highway/**",
    ])
)


filegroup(
    name = "test_scene",
    srcs = glob([
        "test_scene/**",
    ])
)
