load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "utlis",
    srcs = ["utlis.py"],
    deps = [
        "//modules/tools/custom_2/EnvLib:ObstGeomEnv",
    ],
)